(function(g){var window=this;'use strict';var fgb=function(a){g.T.call(this,{G:"div",N:"ytp-miniplayer-ui"});this.Sf=!1;this.player=a;this.S(a,"minimized",this.Uh);this.S(a,"onStateChange",this.EO)},ggb=function(a){g.bS.call(this,a);
this.u=new g.cG(this);this.j=new fgb(this.player);this.j.hide();g.YQ(this.player,this.j.element,4);a.jg()&&(this.load(),g.zo(a.getRootNode(),"ytp-player-minimized",!0));this.player.K("web_rounded_containers")&&g.zo(a.getRootNode(),"ytp-rounded-miniplayer",!0)};
g.v(fgb,g.T);g.k=fgb.prototype;
g.k.FL=function(){this.tooltip=new g.JV(this.player,this);g.D(this,this.tooltip);g.YQ(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Qc=new g.TS(this.player);g.D(this,this.Qc);this.lj=new g.T({G:"div",N:"ytp-miniplayer-scrim"});g.D(this,this.lj);this.lj.Da(this.element);this.S(this.lj.element,"click",this.xG);var a=new g.T({G:"button",Ia:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Fermer"},W:[g.UN()]});g.D(this,a);a.Da(this.lj.element);this.S(a.element,"click",this.Ro);
a=new g.B2(this.player,this);g.D(this,a);a.Da(this.lj.element);this.wu=new g.T({G:"div",N:"ytp-miniplayer-controls"});g.D(this,this.wu);this.wu.Da(this.lj.element);this.S(this.wu.element,"click",this.xG);var b=new g.T({G:"div",N:"ytp-miniplayer-button-container"});g.D(this,b);b.Da(this.wu.element);a=new g.T({G:"div",N:"ytp-miniplayer-play-button-container"});g.D(this,a);a.Da(this.wu.element);var c=new g.T({G:"div",N:"ytp-miniplayer-button-container"});g.D(this,c);c.Da(this.wu.element);this.dW=new g.CU(this.player,
this,!1);g.D(this,this.dW);this.dW.Da(b.element);b=new g.AU(this.player,this);g.D(this,b);b.Da(a.element);this.nextButton=new g.CU(this.player,this,!0);g.D(this,this.nextButton);this.nextButton.Da(c.element);this.nj=new g.CV(this.player,this);g.D(this,this.nj);this.nj.Da(this.lj.element);this.Jc=new g.NU(this.player,this);g.D(this,this.Jc);g.YQ(this.player,this.Jc.element,4);this.nG=new g.T({G:"div",N:"ytp-miniplayer-buttons"});g.D(this,this.nG);g.YQ(this.player,this.nG.element,4);a=new g.T({G:"button",
Ia:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Fermer"},W:[g.UN()]});g.D(this,a);a.Da(this.nG.element);this.S(a.element,"click",this.Ro);a=new g.T({G:"button",Ia:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Fermer"},W:[g.aO()]});g.D(this,a);a.Da(this.nG.element);this.S(a.element,"click",this.v6);this.S(this.player,"presentingplayerstatechange",this.td);this.S(this.player,"appresize",this.Eb);this.S(this.player,"fullscreentoggled",this.Eb);this.Eb()};
g.k.show=function(){this.jf=new g.lo(this.vv,null,this);this.jf.start();this.Sf||(this.FL(),this.Sf=!0);0!==this.player.getPlayerState()&&g.T.prototype.show.call(this);this.Jc.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.jf&&(this.jf.dispose(),this.jf=void 0);g.T.prototype.hide.call(this);this.player.jg()||(this.Sf&&this.Jc.hide(),this.player.loadModule("annotations_module"))};
g.k.ra=function(){this.jf&&(this.jf.dispose(),this.jf=void 0);g.T.prototype.ra.call(this)};
g.k.Ro=function(){this.player.stopVideo();this.player.Na("onCloseMiniplayer")};
g.k.v6=function(){this.player.playVideo()};
g.k.xG=function(a){if(a.target===this.lj.element||a.target===this.wu.element)g.CM(this.player.Fb())?this.player.pauseVideo():this.player.playVideo()};
g.k.Uh=function(){g.zo(this.player.getRootNode(),"ytp-player-minimized",this.player.jg())};
g.k.Ge=function(){this.Jc.xc();this.nj.xc()};
g.k.vv=function(){this.Ge();this.jf&&this.jf.start()};
g.k.td=function(a){g.S(a.state,32)&&this.tooltip.hide()};
g.k.Eb=function(){g.bV(this.Jc,0,this.player.gb().getPlayerSize().width,!1);g.QU(this.Jc)};
g.k.EO=function(a){this.player.jg()&&(0===a?this.hide():this.show())};
g.k.Cc=function(){return this.tooltip};
g.k.hg=function(){return!1};
g.k.gh=function(){return!1};
g.k.Qb=function(){return!1};
g.k.El=function(){return!1};
g.k.oD=function(){};
g.k.Ip=function(){};
g.k.Nx=function(){};
g.k.Dm=function(){return null};
g.k.lF=function(){return null};
g.k.oF=function(){return new g.je(0,0)};
g.k.BB=function(){return null};
g.k.qk=function(){return new g.Cl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Gv=function(a,b,c,d,e){var f=0,h=d=0,l=g.Wl(a);if(b){c=g.uo(b,"ytp-prev-button")||g.uo(b,"ytp-next-button");var m=g.uo(b,"ytp-play-button"),n=g.uo(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Ul(b,this.element),h=b.x,f=b.y-12):n&&(h=g.uo(b,"ytp-miniplayer-button-top-left"),f=g.Ul(b,this.element),b=g.Wl(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.gb().getPlayerSize().width;e=f+(e||0);l=g.be(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};
g.k.showControls=function(){};
g.k.fp=function(){};
g.k.zl=function(){return!1};
g.k.pD=function(){};
g.k.rz=function(){};
g.k.Lq=function(){};
g.k.Kq=function(){};
g.k.uE=function(){};
g.k.Jr=function(){};g.v(ggb,g.bS);g.k=ggb.prototype;g.k.onVideoDataChange=function(){if(this.player.K("web_rounded_containers")&&this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.zo(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.bS.prototype.create.call(this);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.Mk=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.aS("miniplayer",ggb);})(_yt_player);
